services:
  app:
    build: .
    container_name: new-libya-store
    ports:
      - "3000:3000"
    depends_on:
      mongodb-setup:
        condition: service_completed_successfully
      # - mongodb
    restart: unless-stopped
    volumes:
      - .:/app:cached
      - /app/node_modules
    env_file:
      - .env

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    command: "mongod --replSet rs0 --bind_ip_all"
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  mongodb-setup:
    image: mongo:8.0
    container_name: mongodb-setup
    depends_on:
      mongodb:
        condition: service_healthy
    restart: "no"
    command: >
      mongosh --host mongodb:27017 --eval '
        try {
          rs.status();
        } catch (e) {
          rs.initiate({
            _id: "rs0",
            members: [
              { _id: 0, host: "mongodb:27017", priority: 1 }
            ]
          });
        }'

volumes:
  mongodb_data:
    driver: local
